version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_STARTER_PACK_PRICE_ID=${STRIPE_STARTER_PACK_PRICE_ID}
      - STRIPE_MEDIUM_PACK_PRICE_ID=${STRIPE_MEDIUM_PACK_PRICE_ID}
      - STRIPE_LARGE_PACK_PRICE_ID=${STRIPE_LARGE_PACK_PRICE_ID}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}